#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="${0:A:h}"
REPO_DIR="${SCRIPT_DIR:h}"

SETTINGS_FILE="$REPO_DIR/vscode-insiders/settings.json"
README_DIR="$REPO_DIR/vscode-insiders"
README_FILE="$README_DIR/README.md"

CODEX_BIN="${CODEX_BIN:-codex}"
GENERATOR_VERSION="2"

if [[ ! -f "$SETTINGS_FILE" ]]; then
  echo "Missing VS Code Insiders settings: $SETTINGS_FILE" >&2
  exit 1
fi

if ! command -v "$CODEX_BIN" >/dev/null 2>&1; then
  echo "Codex CLI was not found: $CODEX_BIN" >&2
  echo "Install and authenticate the Codex CLI before running this script." >&2
  exit 1
fi

SETTINGS_SHA256="$(shasum -a 256 "$SETTINGS_FILE" | awk '{print $1}')"
SOURCE_MARKER="<!-- settings-sha256:${SETTINGS_SHA256}; generator-version:${GENERATOR_VERSION} -->"

# Avoid spending tokens when neither the settings nor generator version changed.
if [[ -f "$README_FILE" ]] &&
   grep -Fqx "$SOURCE_MARKER" "$README_FILE"; then
  echo "VS Code Insiders README is already up to date."
  exit 0
fi

MODEL_OUTPUT="$(mktemp "$README_DIR/.README.model.XXXXXX")"
NEXT_README="$(mktemp "$README_DIR/.README.next.XXXXXX")"
CODEX_LOG="$(mktemp "$README_DIR/.README.codex-log.XXXXXX")"

cleanup() {
  rm -f "$MODEL_OUTPUT" "$NEXT_README" "$CODEX_LOG"
}
trap cleanup EXIT INT TERM HUP

cd "$REPO_DIR"

{
  cat <<'PROMPT'
Write the complete README.md for the supplied VS Code Insiders settings.json.

Requirements:

- Output Markdown only, with no introductory commentary and no enclosing
  Markdown fence.
- The first line must be exactly:
  # VS Code Insiders Settings
- Explain the purpose and practical effect of every top-level setting in the
  supplied JSON-with-comments file.
- Explain nested objects, language-specific overrides, arrays, regular
  expressions, toggle configurations, and custom dictionaries.
- Group related settings into readable sections such as editor behavior,
  Git, LaTeX, PDF viewing, autosave, spelling, and appearance.
- Show exact setting names and important configured values in inline code.
- Distinguish built-in VS Code settings from extension-provided settings when
  that distinction is reasonably clear.
- Mention that extension-specific settings require the corresponding
  extensions to be installed.
- Include concise restoration instructions for placing settings.json in the
  macOS VS Code Insiders User directory.
- State that settings.json is JSON with Comments (JSONC), since comments are
  present.
- Do not document settings that are absent from the supplied file.
- Do not invent defaults or unsupported behavior. If a setting's precise
  behavior is uncertain, describe it conservatively.
- Do not include secrets, personal information, or claims about the user.
- Do not say that the document was generated by AI, Codex, or ChatGPT.
- Make the result useful both as documentation and as a reviewable summary of
  the configuration.

The complete settings.json follows.

--- BEGIN SETTINGS.JSON ---
PROMPT

  cat "$SETTINGS_FILE"

  cat <<'PROMPT'

--- END SETTINGS.JSON ---
PROMPT
} | "$CODEX_BIN" exec \
      --ephemeral \
      --sandbox read-only \
      - > "$MODEL_OUTPUT" 2> "$CODEX_LOG" || {
  echo "Codex failed to generate the VS Code Insiders README." >&2
  echo "Codex diagnostics after the submitted settings:" >&2

  if grep -Fq -- '--- END SETTINGS.JSON ---' "$CODEX_LOG"; then
    awk '
      found { print }
      /--- END SETTINGS.JSON ---/ { found = 1 }
    ' "$CODEX_LOG" | tail -n 80 >&2
  else
    tail -n 40 "$CODEX_LOG" >&2
  fi

  exit 1
}

if [[ ! -s "$MODEL_OUTPUT" ]]; then
  echo "Codex returned an empty README." >&2
  exit 1
fi

if [[ "$(head -n 1 "$MODEL_OUTPUT")" != "# VS Code Insiders Settings" ]]; then
  echo "Codex returned an unexpected document format." >&2
  echo "The existing README was left unchanged." >&2
  exit 1
fi

if ! grep -Fq "settings.json" "$MODEL_OUTPUT"; then
  echo "Generated README does not appear to describe settings.json." >&2
  echo "The existing README was left unchanged." >&2
  exit 1
fi

{
  printf '%s\n\n' "$SOURCE_MARKER"
  cat "$MODEL_OUTPUT"
} > "$NEXT_README"

# Normalize the generated document to exactly one trailing newline.
perl -0pi -e 's/\s*\z/\n/' "$NEXT_README"

# Replace the README only after validating the generated document.
mv "$NEXT_README" "$README_FILE"

echo "Updated: vscode-insiders/README.md"
